# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path
import sys

block_cipher = None
REPO_ROOT = Path(SPECPATH)

datas = [
    (str(REPO_ROOT / "assets"), "assets"),
    (str(REPO_ROOT / "src" / "arenamcp" / "resources"), "arenamcp/resources"),
    (str(REPO_ROOT / "src" / "arenamcp" / "resources"), "src/arenamcp/resources"),
    (str(REPO_ROOT / "mtga_coach.ico"), "."),
    (str(REPO_ROOT / "icon.ico"), "."),
    (str(REPO_ROOT / "pyproject.toml"), "."),
]

hiddenimports = [
    "arenamcp",
    "arenamcp.action_legality",
    "arenamcp.action_planner",
    "arenamcp.autopilot",
    "arenamcp.autopilot_bridge",
    "arenamcp.autopilot_exec",
    "arenamcp.autopilot_models",
    "arenamcp.autopilot_modes",
    "arenamcp.autopilot_telemetry",
    "arenamcp.backends",
    "arenamcp.backends.base",
    "arenamcp.backends.proxy",
    "arenamcp.coach",
    "arenamcp.coach_analysis",
    "arenamcp.coach_backends",
    "arenamcp.coach_history",
    "arenamcp.coach_postprocess",
    "arenamcp.coach_prompt_utils",
    "arenamcp.coach_prompts",
    "arenamcp.coach_tracker",
    "arenamcp.combat_solver",
    "arenamcp.decision_arbiter",
    "arenamcp.decisions",
    "arenamcp.desktop",
    "arenamcp.desktop.app",
    "arenamcp.desktop.audio",
    "arenamcp.desktop.brain_stream_window",
    "arenamcp.desktop.coach_process",
    "arenamcp.desktop.coach_session",
    "arenamcp.desktop.compact_coach",
    "arenamcp.desktop.hotkeys",
    "arenamcp.desktop.hotkeys_darwin",
    "arenamcp.desktop.main_window",
    "arenamcp.desktop.performance_tab",
    "arenamcp.desktop.repair_tab",
    "arenamcp.desktop.runtime",
    "arenamcp.desktop.setup_splash",
    "arenamcp.desktop.theme",
    "arenamcp.desktop.tts_manager",
    "arenamcp.desktop.tts_worker",
    "arenamcp.desktop.ui_watchdog",
    "arenamcp.desktop.window_tracking",
    "arenamcp.diagnose",
    "arenamcp.draft_eval",
    "arenamcp.draft_guidance",
    "arenamcp.draftstats",
    "arenamcp.gamestate",
    "arenamcp.gamestate_annotations",
    "arenamcp.gamestate_decisions",
    "arenamcp.gamestate_gre",
    "arenamcp.gamestate_log",
    "arenamcp.gamestate_models",
    "arenamcp.gre_action_matcher",
    "arenamcp.gre_bridge",
    "arenamcp.gre_serializer",
    "arenamcp.mana",
    "arenamcp.mtgadb",
    "arenamcp.mtggoldfish",
    "arenamcp.mtgjson",
    "arenamcp.parser",
    "arenamcp.pipe_adapter",
    "arenamcp.platform_integration",
    "arenamcp.repair_engine",
    "arenamcp.rules_data",
    "arenamcp.rules_db",
    "arenamcp.rules_engine",
    "arenamcp.scryfall",
    "arenamcp.sealed_eval",
    "arenamcp.server",
    "arenamcp.settings",
    "arenamcp.standalone",
    "arenamcp.standalone_deck",
    "arenamcp.standalone_diagnostics",
    "arenamcp.standalone_hotkeys",
    "arenamcp.standalone_mcp",
    "arenamcp.standalone_postmatch",
    "arenamcp.standalone_tempo",
    "arenamcp.standalone_ui",
    "arenamcp.standalone_voice",
    "arenamcp.standalone_windows",
    "arenamcp.subscription",
    "arenamcp.synergy",
    "arenamcp.trajectory_recorder",
    "arenamcp.tts",
    "arenamcp.updater",
    "arenamcp.voice",
    "arenamcp.watcher",
    "PySide6",
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "pygetwindow",
    "keyboard",
    "watchdog",
    "mcp",
    "fastmcp",
    "win32gui",
    "win32con",
    "win32process",
    "win32api",
    "urllib3",
    "requests",
]

a = Analysis(
    [str(REPO_ROOT / "src" / "arenamcp" / "desktop" / "app.py")],
    pathex=[str(REPO_ROOT / "src")],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "unittest", "test"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="mtgacoach",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(REPO_ROOT / "mtga_coach.ico") if (REPO_ROOT / "mtga_coach.ico").exists() else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="mtgacoach",
)
